name: Flutter Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.3'

      - name: Create minimal Flutter project
        run: |
          flutter create minimal_flutter_project
          cd minimal_flutter_project
          flutter pub get

      - name: Build APK for arm64
        run: |
          cd minimal_flutter_project
          flutter build apk --release --target-platform android-arm64

      - name: Upload libflutter.so
        uses: actions/upload-artifact@v2
        with:
          name: libflutter_so
          path: minimal_flutter_project/build/app/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libflutter.so
