name: Build Flutter Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'  # Update to the correct Flutter version
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Engine for arm64-v8a
        run: flutter build apk --release --target-platform=android-arm64

      - name: Build Flutter Engine for armeabi-v7a
        run: flutter build apk --release --target-platform=android-arm
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-libs
          path: build/app/outputs/flutter-apk/app-release.apk  # Adjust this path as needed
